[project]
name = "backend"
version = "0.1.0"
description = "Timeline FastAPI backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn[standard]>=0.34.2",
]

[project.scripts]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
